name: Idea Template
description: Template for ideas we may not want to spend too much time formalizing into tasks.
title: "[IDEA] <title>"
labels: ["idea"]
body: 
  - type: textarea
    id: goal-description
    attributes:
      label: Goal Description
      description: A description of what you would like to see implemented, and perhaps how. Can be as vague and informal as you want. However, being descriptive is always appreciated. 😉
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: These should serve as a guide of different ideas or concerns you may have regarding the task, providing some insight of your vision to the programmer working on it.
    