namespace LabApi.Features.Enums;

/// <summary>
/// Represents the door type according to the name of the door or gameobject.
/// </summary>
public enum DoorType
{
    None = 0,
    LczDoor,
    LczPrisonDoor,
    LczGreenhouse,
    LczAirlock,
    LczElevatorA,
    LczElevatorB,
    LczPc,
    LczWc,
    LczCheckpointA,
    LczCheckpointB,
    LczArmory,
    Lcz173Bottom,
    Lcz173Gate,
    Lcz173Connector,
    Lcz173Armory,
    LczGr18Inner,
    LczGr18Gate,
    Lcz914Gate,
    Lcz914Machine,
    Lcz330,
    Lcz330Chamber,
    HczDoor,
    HczBulkDoor,
    HczElevatorA,
    HczElevatorB,
    HczTestroom,
    Hcz079FirstGate,
    Hcz079SecondGate,
    Hcz079Armory,
    Hcz096,
    Hcz939Cryo,
    HczArmory,
    Hcz049Armory,
    Hcz049Elevator,
    Hcz049Gate,
    Hcz173Gate,
    HczHidChamber,
    HczHidLab,
    HczHidUpper,
    HczHidLower,
    HczNukeArmory,
    HczNukeElevator,
    HczServersElevator,
    Hcz106Primiary,
    Hcz106Secondary,
    HczCheckpoint,
    HczCheckpointArmory,
    HczCheckpointGate,
    Hcz127Lab,
    EzDoor,
    EzIntercom,
    EzGateA,
    EzGateB,
    EzGateAElevator,
    EzGateBElevator,
    SurfaceGate,
    SurfaceNuke,
    SurfaceEscapePrimary,
    SurfaceEscapeSecondary,
    SurfaceEscapeFinal,
    ElevatorDoor,
    GateDoor,
}